
name: Node.js CI

on:
  push:
    branches:  
    - master
    - releases/*
  pull_request:
    branches:
    - master
    - releases/*

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
          node: [ 14, 16, 18, 20 ]
    name: Node ${{ matrix.node }} sample
    steps:
    - uses: actions/checkout@v4
      name: Setup node
    # - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    # strategy:
    #   matrix:
    #     node: [ 14, 16, 18 ]
    # name: Node ${{ matrix.node }} sample
    # steps:
    #   - uses: actions/checkout@v4
    #   - name: Setup node
    #     uses: actions/setup-node@v4
    #     with:
    #       node-version: ${{ matrix.node }}